config/routes.rb
Rails.application.routes.draw do
  resources :acts

  resources :amoebas

  post 'amoebas/:id/split' => 'amoebas#split', as: :split_amoeba

end

app/models/act.rb
class Act < ActiveRecord::Base
  has_many :amoeba_acts
  has_many :amoebas, through: :amoeba_acts 
end

app/models/amoeba.rb
class Amoeba < ActiveRecord::Base
  belongs_to :talent
  has_many :amoeba_acts
  has_many :acts, through: :amoeba_acts

  # How to assign the generation to 1 if it is not initialized from split? 

  def split
    2.times do
      self.class.create(
        name: self.name, 
        generation: self.generation+1,
        talent: self.talent,
        acts: self.acts)
    end 
    self.destroy
  end 
end

app/models/amoeba_act.rb
class AmoebaAct < ActiveRecord::Base
  belongs_to :amoeba
  belongs_to :act
end 

app/models/talent.rb
class Talent < ActiveRecord::Base
  has_many :amoebas
end 

app/controllers/acts_controller.rb
class ActsController < ApplicationController
  before_action :set_act, only: [:show, :edit, :update, :destroy]

  # GET /acts
  # GET /acts.json
  def index
    @acts = Act.all
  end

  # GET /acts/1
  # GET /acts/1.json
  def show
  end

  # GET /acts/new
  def new
    @act = Act.new
  end

  # GET /acts/1/edit
  def edit
  end

  # POST /acts
  # POST /acts.json
  def create
    @act = Act.new(act_params)

    respond_to do |format|
      if @act.save
        format.html { redirect_to @act, notice: 'Act was successfully created.' }
        format.json { render :show, status: :created, location: @act }
      else
        format.html { render :new }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acts/1
  # PATCH/PUT /acts/1.json
  def update
    respond_to do |format|
      if @act.update(act_params)
        format.html { redirect_to @act, notice: 'Act was successfully updated.' }
        format.json { render :show, status: :ok, location: @act }
      else
        format.html { render :edit }
        format.json { render json: @act.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acts/1
  # DELETE /acts/1.json
  def destroy
    @act.destroy
    respond_to do |format|
      format.html { redirect_to acts_url, notice: 'Act was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_act
      @act = Act.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def act_params
      params.require(:act).permit(:name, :time_of_performance, amoeba_ids: [])
    end
end

app/controllers/amoebas_controller.rb
class AmoebasController < ApplicationController
  before_action :set_amoeba, only: [:split, :show, :edit, :update, :destroy]

  def split
    @amoeba.split

    respond_to do |format|
      format.html { redirect_to amoebas_url, notice: 'Amoeba was successfully split.' }
      format.json { head :no_content }
    end
  end 

  # GET /amoebas
  # GET /amoebas.json
  def index
    @amoebas = Amoeba.all
  end

  # GET /amoebas/1
  # GET /amoebas/1.json
  def show
  end

  # GET /amoebas/new
  def new
    @amoeba = Amoeba.new
  end

  # GET /amoebas/1/edit
  def edit
  end

  # POST /amoebas
  # POST /amoebas.json
  def create
    @amoeba = Amoeba.new(amoeba_params)

    respond_to do |format|
      if @amoeba.save
        format.html { redirect_to @amoeba, notice: 'Amoeba was successfully created.' }
        format.json { render :show, status: :created, location: @amoeba }
      else
        format.html { render :new }
        format.json { render json: @amoeba.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amoebas/1
  # PATCH/PUT /amoebas/1.json
  def update
    respond_to do |format|
      if @amoeba.update(amoeba_params)
        format.html { redirect_to @amoeba, notice: 'Amoeba was successfully updated.' }
        format.json { render :show, status: :ok, location: @amoeba }
      else
        format.html { render :edit }
        format.json { render json: @amoeba.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amoebas/1
  # DELETE /amoebas/1.json
  def destroy
    @amoeba.destroy
    respond_to do |format|
      format.html { redirect_to amoebas_url, notice: 'Amoeba was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amoeba
      @amoeba = Amoeba.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amoeba_params
      params.require(:amoeba).permit(:name, :generation, :talent_id, act_ids: [])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/helpers/amoebas_helper.rb
module AmoebasHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/acts/_form.html.erb
<%= form_for(@act) do |f| %>
  <% if @act.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@act.errors.count, "error") %> prohibited this act from being saved:</h2>

      <ul>
      <% @act.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :time_of_performance %><br>
    <%= f.datetime_select :time_of_performance, :ampm => true, :minute_step => 15 %>
  </div>
  <div>
    <%= f.label :amoeba_ids %><br>
    <%= f.collection_check_boxes :amoeba_ids, Amoeba.all, :id, :name %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/acts/edit.html.erb
<h1>Editing act</h1>

<%= render 'form' %>

<%= link_to 'Show', @act %> |
<%= link_to 'Back', acts_path %>

app/views/acts/index.html.erb
<h1>Listing acts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @acts.each do |act| %>
      <tr>
        <td><%= act.name %></td>
        <td><%= link_to 'Show', act %></td>
        <td><%= link_to 'Edit', edit_act_path(act) %></td>
        <td><%= link_to 'Destroy', act, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Act', new_act_path %>

app/views/acts/new.html.erb
<h1>New act</h1>

<%= render 'form' %>

<%= link_to 'Back', acts_path %>

app/views/acts/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @act.name %></h1>

<p><%= @act.name %> is happening at <%= @act.time_of_performance %>.</p>

<% if @act.amoebas.size > 0 %>
  <p><%= @act.name %>'s amoebas are:</p>

  <table>
    <thead>
      <tr>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
        <tr>
          <td><strong>Name</strong></td>
          <td><strong>Generation</strong></td>
          <td><strong>Talent</strong></td>
        </tr>
      <% @act.amoebas.each do |amoeba| %>
        <tr>
          <td><%= amoeba.name %></td>
          <td><%= amoeba.generation %></td>
          <td><%= amoeba.talent.name %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
<% end %>

<%= link_to 'Edit', edit_act_path(@act) %> |
<%= link_to 'Back', acts_path %>

app/views/amoebas/_form.html.erb
<%= form_for(@amoeba) do |f| %>
  <% if @amoeba.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amoeba.errors.count, "error") %> prohibited this amoeba from being saved:</h2>

      <ul>
      <% @amoeba.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :generation %><br>
    <%= f.number_field :generation %>
  </div>
  <div class="field">
    <%= f.label :talent_id %><br>
    <%= f.collection_select :talent_id, Talent.all, :id, :name %>
  </div>
  <div>
    <%= f.label :act_ids %><br>
    <%= f.collection_check_boxes :act_ids, Act.all, :id, :name %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/amoebas/edit.html.erb
<h1>Editing amoeba</h1>

<%= render 'form' %>

<%= link_to 'Show', @amoeba %> |
<%= link_to 'Back', amoebas_path %>

app/views/amoebas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing amoebas</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><strong>Name</strong></td>
        <td><strong>Generation</strong></td>
        <td><strong>Talent</strong></td>
      </tr>
    <% @amoebas.each do |amoeba| %>
      <tr>
        <td><%= amoeba.name %></td>
        <td><%= amoeba.generation %></td>
        <td><%= amoeba.talent.name %></td>

        <td><%= link_to 'Split', split_amoeba_path(amoeba), method: "post" %></td>
        <td><%= link_to 'Show', amoeba %></td>
        <td><%= link_to 'Edit', edit_amoeba_path(amoeba) %></td>
        <td><%= link_to 'Destroy', amoeba, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

<%= link_to 'New Amoeba', new_amoeba_path %>

app/views/amoebas/new.html.erb
<h1>New amoeba</h1>

<%= render 'form' %>

<%= link_to 'Back', amoebas_path %>

app/views/amoebas/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @amoeba.name %></h1>

<p>
  <%= @amoeba.name %>'s talent is <%= @amoeba.talent.name %><br>
  <%= @amoeba.name %>'s generation is <%= @amoeba.generation %><br>
  <% if @amoeba.acts.size > 0 %>
    <%= @amoeba.name %> is part of the following acts:
    <ul>
      <% @amoeba.acts.each do |act| %>
        <li><%= act.name %></li>
      <% end %>
    </ul>
  <% end %>
</p>

<%= form_tag split_amoeba_path(@amoeba) do -%>
  <%= submit_tag "Split #{@amoeba.name}?" %>
<% end %><br>

<%= link_to 'Edit', edit_amoeba_path(@amoeba) %> |
<%= link_to 'Back', amoebas_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AmoebaApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>